import { Category, ProductWithCategory } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Įkrovimo stotelės', slug: 'chargers', sort_order: 1 },
  { id: 'cat-2', name: 'Inverteriai', slug: 'inverters', sort_order: 2 },
  { id: 'cat-3', name: 'Saulės moduliai', slug: 'solar-panels', sort_order: 3 },
  { id: 'cat-4', name: 'Montavimo sistema', slug: 'mounting', sort_order: 4 },
  { id: 'cat-5', name: 'Kita', slug: 'other', sort_order: 999 },
];

export const MOCK_PRODUCTS: ProductWithCategory[] = [
  // Charging stations (Įkrovimo stotelės)
  {
    id: 'prod-1',
    sku: 'WP-HOME-11',
    name: 'Fronius Wattpilot Home 11 kW',
    unit_price: 899,
    category_id: 'cat-1',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-2',
    sku: 'WP-HOME-22',
    name: 'Fronius Wattpilot Home 22 kW',
    unit_price: 1249,
    category_id: 'cat-1',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-3',
    sku: 'EV-BOX-7.4',
    name: 'EVBox Elvi 7.4 kW įkrovimo stotelė',
    unit_price: 749,
    category_id: 'cat-1',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-4',
    sku: 'WALLBOX-22',
    name: 'Wallbox Pulsar Plus 22 kW',
    unit_price: 995,
    category_id: 'cat-1',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
  },

  // Inverters (Inverteriai)
  {
    id: 'prod-5',
    sku: 'FR-SYMO-10',
    name: 'Fronius Symo 10.0-3-M',
    unit_price: 2450,
    category_id: 'cat-2',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-6',
    sku: 'FR-PRIMO-5',
    name: 'Fronius Primo 5.0-1',
    unit_price: 1650,
    category_id: 'cat-2',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-7',
    sku: 'HW-SUN-10',
    name: 'Huawei SUN2000-10KTL-M1',
    unit_price: 2150,
    category_id: 'cat-2',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-8',
    sku: 'SOL-S5-GR1',
    name: 'SolarEdge SE5K-RWS SetApp',
    unit_price: 1890,
    category_id: 'cat-2',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
  },

  // Solar panels (Saulės moduliai)
  {
    id: 'prod-9',
    sku: 'LONGI-430',
    name: 'Longi Hi-MO 6 430W',
    unit_price: 165,
    category_id: 'cat-3',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-10',
    sku: 'JA-SOLAR-455',
    name: 'JA Solar JAM72S30 455W',
    unit_price: 172,
    category_id: 'cat-3',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-11',
    sku: 'TRINA-505',
    name: 'Trina Vertex S 505W',
    unit_price: 185,
    category_id: 'cat-3',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-12',
    sku: 'QCELLS-425',
    name: 'Q.PEAK DUO BLK ML-G10+ 425W',
    unit_price: 178,
    category_id: 'cat-3',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
  },

  // Mounting system (Montavimo sistema)
  {
    id: 'prod-13',
    sku: 'K2-SR36',
    name: 'K2 SingleRail 36 montavimo sistema',
    unit_price: 890,
    category_id: 'cat-4',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
  },
  {
    id: 'prod-14',
    sku: 'SCHLETTER-SOLO',
    name: 'Schletter Solo montavimo sistema',
    unit_price: 945,
    category_id: 'cat-4',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
  },
  {
    id: 'prod-15',
    sku: null,
    name: 'Montavimo darbai (stogo montavimas)',
    unit_price: 1200,
    category_id: 'cat-4',
    vat_rate: 0.21,
    is_service: true,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
  },
  {
    id: 'prod-16',
    sku: null,
    name: 'Montavimo darbai (žemės montavimas)',
    unit_price: 950,
    category_id: 'cat-4',
    vat_rate: 0.21,
    is_service: true,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
  },
  {
    id: 'prod-17',
    sku: null,
    name: 'Elektros instaliacijos darbai',
    unit_price: 850,
    category_id: 'cat-4',
    vat_rate: 0.21,
    is_service: true,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
  },

  // Other (Kita)
  {
    id: 'prod-18',
    sku: 'DC-PROT-01',
    name: 'DC apsauga',
    unit_price: 45,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-19',
    sku: 'AC-PROT-01',
    name: 'AC apsauga',
    unit_price: 65,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-20',
    sku: 'CABLE-6MM',
    name: 'Saulės kabelis 6mm² (metras)',
    unit_price: 3.5,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-21',
    sku: 'MC4-CONN',
    name: 'MC4 jungtys (pora)',
    unit_price: 4.2,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-22',
    sku: 'GROUNDING-SET',
    name: 'Įžeminimo komplektas',
    unit_price: 89,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: false,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-23',
    sku: null,
    name: 'Projektavimo darbai',
    unit_price: 450,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: true,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-24',
    sku: null,
    name: 'Priežiūros paslauga (1 metai)',
    unit_price: 290,
    category_id: 'cat-5',
    vat_rate: 0.21,
    is_service: true,
    is_internal_only: false,
    collapse_into_materials: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
];

// Helper function to get category by slug
export function getCategoryBySlug(slug: string): Category | undefined {
  return MOCK_CATEGORIES.find((cat) => cat.slug === slug);
}

// Helper function to get products by category
export function getProductsByCategory(categorySlug: string): ProductWithCategory[] {
  return MOCK_PRODUCTS.filter((prod) => prod.category?.slug === categorySlug);
}

// Helper function to get all products
export function getAllProducts(): ProductWithCategory[] {
  return MOCK_PRODUCTS;
}
